import { Calendar } from '@fullcalendar/core';
import { calendarOptions } from '../shared/calendar.js';
import { responseError } from '../shared/errors.js';
import { DateTime } from 'luxon';
const csrf = document.querySelector('meta[name="csrf-token"]')?.content;
const el = document.querySelector('#calendar');
if(el){
 const dialog=document.querySelector('#reschedule-dialog'),form=document.querySelector('#reschedule-form');let pending;
 const close=()=>{if(pending)pending.revert();pending=null;dialog.close();};
 const calendar=new Calendar(el,{...calendarOptions,initialView:window.innerWidth<600?'timeGridDay':'dayGridMonth',editable:el.dataset.supervisor==='1',eventDurationEditable:false,eventStartEditable:true,eventSources:[{url:'/calendar/events',extraParams:()=>Object.fromEntries(new FormData(document.querySelector('#calendar-filters'))),failure:()=>{document.querySelector('#calendar-message').textContent='Calendar could not load. Please refresh or sign in again.';}}],dateClick:info=>{if(el.dataset.supervisor==='1')location.href='/tasks/create?date='+info.dateStr.slice(0,10);},eventDrop:info=>{pending=info;form.reset();const previous=DateTime.fromISO(info.oldEvent.startStr);const shift=DateTime.fromISO(info.event.startStr).toMillis()-previous.toMillis();const due=DateTime.fromISO(info.oldEvent.extendedProps.due_at).plus({milliseconds:shift}).setZone('Africa/Johannesburg');form.elements.due_at.value=due.toFormat("yyyy-MM-dd'T'HH:mm");document.querySelector('#reschedule-title').textContent=info.event.title;document.querySelector('#reschedule-error').textContent='';dialog.showModal();},eventClick:info=>{info.jsEvent.preventDefault();location.href=info.event.url;}});
 calendar.render();document.querySelector('#calendar-filters').addEventListener('submit',e=>{e.preventDefault();calendar.refetchEvents();});document.querySelector('#reschedule-cancel').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 form.onsubmit=async e=>{e.preventDefault();if(!pending)return;const button=form.querySelector('button');button.disabled=true;try{const body=new FormData(form);body.append('action','reschedule');const r=await fetch('/tasks/'+pending.event.id+'/action',{method:'POST',headers:{'X-CSRF-TOKEN':csrf,'Accept':'application/json'},body});if(!r.ok){const data=await r.json();throw new Error(responseError(data,'Unable to reschedule.'));}pending.revert();pending=null;dialog.close();calendar.refetchEvents();}catch(err){document.querySelector('#reschedule-error').textContent=err.message;}finally{button.disabled=false;}};
}
document.querySelectorAll('[data-upload]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const xhr=new XMLHttpRequest(),progress=form.querySelector('progress'),status=form.querySelector('[data-upload-status]'),button=form.querySelector('button');progress.hidden=false;button.disabled=true;status.textContent='Uploading…';xhr.open('POST',form.action);xhr.setRequestHeader('X-CSRF-TOKEN',csrf);xhr.setRequestHeader('Accept','application/json');xhr.upload.onprogress=e=>{if(e.lengthComputable)progress.value=100*e.loaded/e.total;};xhr.onload=()=>{button.disabled=false;if(xhr.status>=200&&xhr.status<300){status.textContent='Uploaded. Refreshing evidence…';location.reload();}else{try{const data=JSON.parse(xhr.responseText);status.textContent=responseError(data,'Upload failed.');}catch{status.textContent='Upload failed. Check the file size and try again.';}}};xhr.onerror=()=>{button.disabled=false;status.textContent='Network error. Please try again.';};xhr.send(new FormData(form));}));
